[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100

[variables]
PORT = "80"
BACKEND_URL = "https://practical-grace-production.up.railway.app"
